# General
alias open='xdg-open'
alias tl='trash-list'
alias te='trash-empty'
alias ls='lsd'
alias se='ddgr -n 5'
alias duck='w3m -4 https://lite.duckduckgo.com/lite'
alias yt='ytfzf'
alias weather='curl wttr.in/Culiacan\?m\&format=3'
alias clock='tty-clock -c -s -b'
alias suse='sudo zypper refresh && sudo zypper update && sudo zypper dup'
alias off='systemctl poweroff'
alias restart='systemctl reboot'
alias python='python3'
alias angeles='ivpn connect -l "us-ca.wg.ivpn.net"'
alias vegas='ivpn connect -l "us-nv.wg.ivpn.net"'
alias queretaro='ivpn connect -l "mx.wg.ivpn.net"'
alias gemma='ollama run gemma:7b --verbose'
alias haiku='gpt --model claude-3-haiku-20240307'
alias sonnet='gpt --model claude-3-5-sonnet-20240620'
